version: "3"

services: 
  valheim: 
    image: ghcr.io/lloesche/valheim-server:latest
    cap_add:
      - sys_nice
    volumes: 
      - ${HOME}/config:/config
      - ${HOME}/data:/opt/valheim
    ports: 
      - "2456-2458:2456-2458/udp"
      - "9001:9001/tcp"
    env_file:
      - ${HOME}/valheim.env
    restart: always
    stop_grace_period: 2m