version: "3"

services: 
  valheim: 
    image: ghcr.io/lloesche/valheim-server:latest
    hostname: "valheim-server"
    container_name: "valheim-server"    
    cap_add:
      - sys_nice
    volumes: 
      - ${SERVER_FILES}/config:/config
      - ${SERVER_FILES}/data:/opt/valheim
    ports: 
      - "2456-2458:2456-2458/udp"
      - "9001:9001/tcp"
      - "9002:9002/tcp"
    env_file:
      - ${SERVER_FILES}/valheim.env
    restart: always
    stop_grace_period: 2m